swagger: '2.0'

info:
  version: NA
  title: LSM6DS3 - Movesense-API
  description: |
    This API enables configuration of the LSM6DS3 chip.
  x-api-type: private
  x-api-required: false

paths:
  /Component/LSM6DS3/WakeUp:
    get:
      description: |
        Get the active wake-up trigger state
      responses:
        200:
          description: |
            Current wake-up trigger state
          schema:
            $ref: '#/definitions/WakeUpState'
    put:
      description: |
      parameters:
        - name: newState
          in: body
          description: New trigger state
          required: true
          schema:
            $ref: '#/definitions/WakeUpState'
      responses:
        200:
          description: |
            State updated successfully
        400:
          description: |
            Not able to set the wake-up trigger

  /Component/LSM6DS3/TapParams:
    get:
      description: |
        Get the current tap parameters
      responses:
        200:
          description: |
            Current tap parameters
          schema:
            $ref: '#/definitions/TapParams'
        500:
          description: |
            Error getting tap params
    put:
      description: |
      parameters:
        - name: newParams
          in: body
          description: New tap parameters
          required: true
          schema:
            $ref: '#/definitions/TapParams'
      responses:
        200:
          description: |
            Tap parameters updated successfully
          schema:
            $ref: '#/definitions/TapParams'
        400:
          description: |
            Invalid parameters given, not updated
        500:
          description: |
            Error putting tap params

definitions:
  WakeUpState:
    type: object
    required:
      - state
      - level
    properties:
      state:
        description: |
          Wake-up trigger (valid only in PowerOff and FullPowerOff modes)
          0 = no wakeup
          1 = WAKE_UP (any movement)
            level: 0 - 63 (threshold)
          2 = DOUBLE_TAP (Z axis)
            level: 0 - 7 (delay between taps)
          3 = SINGLE_TAP (Z axis)
          4 = FREE_FALL
            level: 0 = 156 mg, 7 = 500 mg
        type: integer
        format: uint8
      level:
        description: |
          0 = default level
          other = wake-up trigger level (see above)
        type: integer
        format: uint8

  TapParams:
    type: object
    properties:
      doubleTapDur:
        description: |
          Duration of maximum time gap for double tap recognition. Default:_ 0000
          When double tap recognition is enabled, this register expresses the maximum time
          between two consecutive detected taps to determine a double tap event. The
          default value of these bits is 0000b which corresponds to 16*ODR_XL time. If the
          DUR[3:0] bits are set to a different value, 1LSB corresponds to 32*ODR_XL time.
        type: integer
        format: uint8
        minimum: 0
        maximum: 15
      doubleTapQuiet:
        description: |
          Expected quiet time after a tap detection. Default value:_ 00
          Quiet time is the time after the first detected tap in which there must not be any
          overthreshold event. The default value of these bits is 00b which corresponds to
          2*ODR_XL time. If the QUIET[1:0] bits are set to a different value, 1LSB
          corresponds to 4*ODR_XL time.
        type: integer
        format: uint8
        minimum: 0
        maximum: 3
      tapThs:
        description: |
          Threshold for tap & double tap recognition. Default value:_ 00000
          1 LSb corresponds to FS_XL/2^5
        type: integer
        format: uint8
        minimum: 0
        maximum: 31
      axes:
        description: |
          Tap detection enabled axes as bitfield:_ x=8, y=4, z=2
        type: integer
        format: uint8
        minimum: 0
        maximum: 14

