swagger: '2.0'

info:
  version: NA
  title: LSM6DS3 - Movesense-API
  description: |
    This API enables configuration of the LSM6DS3 chip.
  x-api-type: private
  x-api-required: false

paths:
  /Component/LSM6DS3/Mode:
    get:
      description: Get the current LSM6DS3 operation mode.
      responses:
        200:
          description: Current LSM6DS3 operation mode
          schema:
            $ref: '#/definitions/LSM6DS3OperationMode'

  /Component/LSM6DS3/Mode/Subscription:
    post:
      description: |
        Subscribe to changes in the LSM6DS3 operation mode.
      responses:
        200:
          description: |
            Subscription successful with current state. Changes in operation
            mode will be delivered.
          schema:
            $ref: '#/definitions/LSM6DS3OperationMode'
        x-notification:
          description: Current operation mode after change
          schema:
            $ref: '#/definitions/LSM6DS3OperationMode'
    delete:
      description: |
        Unsubscribe from changes in the LSM6DS3 operation mode.
      responses:
        200:
          description: Unsubscribe was successfull

  /Component/LSM6DS3/RawEnabled:
    get:
      description: |
        Get the status of raw mode activation.
      responses:
        200:
          description: Boolean true if raw mode is enabled
          schema:
            type: boolean
    put:
      description: |
        Enable or disable raw mode for the component.
        Measurements produced in raw mode are not affected by calibration.
      parameters:
        - name: value
          in: query
          description: New raw mode state
          required: true
          type: boolean
      responses:
        200:
          description: Operation completed successfully

  /Component/LSM6DS3/TiltCompensationEnabled:
    get:
      description: |
        Get info if tilt compensation is enabled
      responses:
        200:
          description: Boolean true if tilt compensation is enabled
          schema:
            type: boolean
    put:
      description: |
        Enable or disable tilt compensation for the accelerometer values.
      parameters:
        - name: value
          in: query
          description: New tilt compensation state
          required: true
          type: boolean
      responses:
        200:
          description: Operation completed successfully

  /Component/LSM6DS3/AutoPassiveEnabled:
    get:
      description: |
        Get indicator whether automatic active to passive PM mechanism is
        enabled.
      responses:
        200:
          description: Boolean true if auto active->passive is enabled
          schema:
            type: boolean
        204:
          description: Component is unavailable
        501:
          description: Not supported
    put:
      description: |
        Enable or disable automatic active-to-passive mechanism.
      parameters:
        - name: value
          in: query
          description: Enable (if true) or disable active-to-passive transition
          required: true
          type: boolean
      responses:
        200:
          description: Operation completed successfully
        204:
          description: Component is unavailable, request is ignored
        501:
          description: Not supported

  /Component/LSM6DS3/WakeUp:
    get:
      description: |
        Get the active wake-up trigger state
      responses:
        200:
          description: |
            Current wake-up trigger state
          schema:
            $ref: '#/definitions/WakeUpState'
    put:
      description: |
      parameters:
        - name: newState
          in: body
          description: New trigger state
          required: true
          schema:
            $ref: '#/definitions/WakeUpState'
      responses:
        200:
          description: |
            State updated successfully
          schema:
            $ref: '#/definitions/WakeUpState'
        400:
          description: |
            Not able to set the wake-up trigger

definitions:
  LSM6DS3OperationMode:
    type: integer
    format: uint8
    enum:
      # Operation modes
      - name: 'Passive'
        description: |
          No subscribers for periodic measurement data, or no movement has been
          detected and periodic measurements are paused. Will change
          automatically to Active mode upon new periodic measurement
          subscription (if there were no periodic measurement subscribers
          previously) or movement detection.
        value: 0
      - name: 'Active'
        description: |
          Active measurement mode in which periodic measurements are sent to any
          subscribers. After a specific period of time of no detected movement
          will switch to Passive mode automatically.
        value: 1
  WakeUpState:
    type: object
    required:
      - state
      - level
    properties:
      state:
        description: |
          Wake-up trigger (valid only in PowerOff and FullPowerOff modes)
          0 = no wakeup
          1 = WAKE_UP (any movement)
            level: 0 - 63 (threshold)
          2 = DOUBLE_TAP (Z axis)
            level: 0 - 7 (delay between taps)
          3 = SINGLE_TAP (Z axis)
          4 = FREE_FALL
            level: 0 = 156 mg, 7 = 500 mg
        type: integer
        format: uint8
      level:
        description: |
          0 = default level
          other = wake-up trigger level (see above)
        type: integer
        format: uint8
