# This file defines Suunto Whiteboard API
#
# Copyright Suunto Oy 2015
# All rights reserved.
#
# Swagger editor is located at http://vaas1410:81/#/
#
# NOTE! Editor remembers last file you have edited, but it is
# not necessarily the version located in your local or shared repository. 
# ALWAYS USE COPY + PASTE TO UPDATE THE EDITOR BEFORE DOING ANY EDITING!!!
#
swagger: '2.0'

# Document metadata
info:
  version: "0.0.0"
  title: Suunto SmartSensor2 DataLogger API
  description: |
    This file defines Suunto API for generic DataLogger module

    See http://developer.suunto.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com
  
# Security definitions
security:
  - suuntoAccessCode:
    - public
    - read:user
    - write:user
    - read:contacts
    - write:contacts
    - test

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
      read:user: Grants read access to user profile info.
      write:user: Grants write access to user profile info.
      read:contacts: Grants read access to user's contants and memberships.
      write:contacts: Grants write access to user's contants and memberships.
      test: Grants read/write access to QA / test resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token
    
# Paths
paths:
  /DataLogger/Config:
    x-executionContext: application
    get:
      description: |
        Reads config from DataLogger.
      responses:
        200:
          description: Operation completed successfully
          schema:
            $ref: '#/definitions/DataLoggerConfig'
        400:
          description: Bad request. Memory could not be read from specified offset.
      security:
        - suuntoAccessCode:
          - test          
    put:
      description: |
        Writes new DataLogger config to device.
      parameters:
        -
          name: config
          in: body
          description: New configuration for DataLogger
          required: true
          schema:
            $ref: '#/definitions/DataLoggerConfig'
      responses:
        200:
          description: Operation completed successfully
        400:
          description: Bad request.
      security:
        - suuntoAccessCode:
          - test     
    

  /DataLogger/State:
    x-executionContext: application
    get:
      description: |
        Reads current DataLogger state.
      responses:
        200:
          description: Operation completed successfully
          schema:
            $ref: '#/definitions/DataLoggerState'        
      security:
        - suuntoAccessCode:
          - test          
    put:
      description: |
        Changes DataLogger to a new state.
      parameters:
        -
          name: newState
          in: body
          description: New state for DataLogger
          required: true
          schema:
            $ref: '#/definitions/DataLoggerState'
      responses:
        200:
          description: Operation completed successfully
        400:
          description: Bad request.
      security:
        - suuntoAccessCode:
          - test     
    

# Extra definitions
definitions:
  DataLoggerConfig:
    required:
      - dataEntries
    properties:
      dataEntries:
        description: Array of structs containing wb-paths to the subscription of data to log.
        $ref: '#/definitions/DataEntryArray'

  DataEntryArray:
    required:
      - dataEntry
    properties:
      dataEntry:
        type: array
        items:
          $ref: '#/definitions/DataEntry'
          
  DataEntry:
    required:
      - path
    properties:
      path:
        type: string
  
  DataLoggerState:
    description: |
      State of the DataLogger component.
    type: integer
    format: uint8
    enum:
      - name: 'DATALOGGER_INVALID'
        description: Unknown or Invalid state prior to initialization or due to comm error.
        value: 1
      - name: 'DATALOGGER_READY'
        description: If we are ready for logging.
        value: 2
      - name: 'DATALOGGER_LOGGING'
        description: If we are logging data.
        value: 3