swagger: '2.0'

info:
  version: 0.0.9
  title: API for device calibration
  description: |
    This file defines API for putting the device into calibration mode.

# Security definitions (these are for future use)
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://movesense.com/wbapi/login/oauth/authorize
    tokenUrl: https://movesense.com/wbapi/login/oauth/access_token

paths:
  /Device/Calibration/Mode:
    put:
      description: |
        Set calibration mode
      parameters:
        - name: mode
          in: query
          description: |
            0: no mode set, 1: PREDEFINED_TILT_SEQUENCE, 2: PREDEFINED_MAGNETIC_FIELD_SEQUENCE, 3: RANDOM_TILT_SEQUENCE (user)
          type: integer
          minimum: 0
          maximum: 3
          required: true
          format: uint8
      responses:
        200:
          description: Mode set succefully and device ready to proceed.
        500:
          description: Not permitted in this state or failed to change mode.
      security:
        - suuntoAccessCode:
          - public

  /Device/Calibration/References:
    put:
      description: Set the local calibration references. Initial sequence start position is (0,0,1).
      parameters:
        - name: gravity
          in: query
          description: Reference gravity during the sequence
          type: number
          default: 9.81
          minimum: 9
          maximum: 10
          x-unit: m/s^2
          format: float
          required: true
        - name: magneticField
          in: query
          description: Reference magnetic field during the sequence
          type: number
          default: 100
          minimum: 0
          maximum: 1000
          x-unit: uT
          format: float
          required: true
        - name: aveSamplesAcceleration
          in: query
          description: # of samples for acceleration average estimation
          type: integer
          default: 10
          minimum: 0
          maximum: 1000
          format: uint8
          required: true
        - name: aveSamplesMagneticField
          in: query
          description: # of samples for magnetic field average estimation
          type: integer
          default: 10
          minimum: 0
          maximum: 1000
          format: uint8
          required: true
      responses:
        200:
          description: Local references updated succefully.
        500:
          description: Not permitted in this state
      security:
        - suuntoAccessCode:
          - public

  /Device/Calibration/Sequence:
    put:
      description: Set the calibration sequence (tilt or magnetic field depending on the set mode)
      parameters:
        - name: sequence
          in: body
          required: true
          schema:
            $ref: 'http://localhost:9000/suunto_shared.yaml#/definitions/FloatVector3DArray'
      responses:
        200:
          description: Operation completed successfully
        500:
          description: Not permitted in this state or not sufficient sequence to perform calibration
      security:
        - suuntoAccessCode:
          - public

  /Device/Calibration/State:
    put:
      description: |
        Set the calibration state. Used in modes 1 and 2 by the calibrator to tell the device. In mode 3 the device itself changes the state. Responses may take time (especially for the SEQUENCE_DONE) and hence the set timeouts may need tuning.
      parameters:
        - name: state
          in: query
          type: integer
          description: |
            0: IDLE, 1: SEQUENCE_ON, 2: STEP_ON, 3: STEP_DONE, 4: SEQUENCE_DONE
          default: 0
          minimum: 0
          maximum: 4
          required: true
          format: uint8
      responses:
        200:
          description: State changed and device ready to proceed.
        500:
          description: Not permitted
      security:
        - suuntoAccessCode:
          - public
    get:
      description: |
        Get the current calibration state
      responses:
        200:
          description:  |
            Calibration state the device is currently at.
          schema:
            type: integer
            format: uint8
        500:
          description: General error
      security:
        - suuntoAccessCode:
          - public
