swagger: '2.0'

info:
  version: 0.0.9
  title: Movesense API for getting temperature
  description: |
    API for getting and subscribing Movesense device internal temperature

# Security definitions (these are for future use)
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://movesense.com/wbapi/login/oauth/authorize
    tokenUrl: https://movesense.com/wbapi/login/oauth/access_token

paths:
  /Device/Measurement/Temperature:
    x-executionContext: meas
    get:
      description: |
        Get the current temperature value in Kelvins
      responses:
        200:
          description: Temperature value with optional timestamp
          schema:
            $ref: '#/definitions/TemperatureValue'
        204:
          description: Measurement source is unavailable
      security:
        - suuntoAccessCode:
          - public

  /Device/Measurement/Temperature/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to periodic temperature readings. The measurement interval can be specified as a parameter. In case no Internal is specified, notifications are given every time the temperature changes in Kelvins.
      parameters:
        - name: Interval
          in: body
          required: false
          description: Reporting period in seconds
          schema:
            type: integer
            format: uint8
            minimum: 1
            maximum: 256
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes at http://bitbucket.org/movesense-device-lib/api/std-errors#subscribe
        x-notification:
          description: The latest reading
          schema:
            $ref: '#/definitions/TemperatureValue'
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Cancel the subscription
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes at http://bitbucket.org/movesense-device-lib/api/std-errors#subscribe
      security:
        - suuntoAccessCode:
          - public

definitions:
  TemperatureValue:
    required:
      - RelativeTime
      - Measurement
    properties:
      RelativeTime:
        description: Relative time of the measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Measurement:
        description: Temperature measurement in kelvins
        type: number
        format: float
        # These are updated based on the device spcific implementation requirement
        minimum: 0
        maximum: 373
        x-unit: kelvin