swagger: '2.0'

info:
    version: 0.0.1
    title: Angular velocity (Movesense-API)
    description: |
      This file defines interface for the angular velocity API.

paths:
  /Meas/Gyro/Info:
    x-executionContext: meas
    get:
      description: |
        Get supported sample rates and ranges.
      responses:
        200:
          description: Returns gyroscope information. See GyroInfo.
          schema:
            $ref: '#/definitions/GyroInfo'

  /Meas/Gyro/Config:
    x-executionContext: meas
    get:
      description: |
        Get current gyroscope measurement configuration.
      responses:
        200:
          description: Returns gyroscope configurations. See GyroConfig.
          schema:
            $ref: '#/definitions/GyroConfig'

    put:
      description: |
        Set current gyroscope measurement configuration.
      parameters:
        - name: config
          in: body
          description: New configurations for gyroscope
          required: true
          schema:
            $ref: '#/definitions/GyroConfig'
      responses:
        200:
          description: Operation completed successfully
        503:
          description: |
            Not allowed to change configuration at the moment. E.g. when
            active subcriptions exist.

  /Meas/Gyro/{SampleRate}:
    x-executionContext: meas
    parameters:
       - $ref: '#/parameters/SampleRate'

  /Meas/Gyro/{SampleRate}/Subscription:
    x-executionContext: meas
    parameters:
       - $ref: '#/parameters/SampleRate'
    post:
      description: |
        Subscribe to periodic gyroscope measurements.
      responses:
        200:
          description: Operation completed successfully
        501:
          description: Non-supported sample rate
        x-notification:
          description: New measurements
          schema:
            $ref: '#/definitions/GyroData'
    delete:
      description: Unsubscribe from periodic gyroscope values.
      responses:
        200:
          description: Operation completed successfully

parameters:
  SampleRate:
    name: SampleRate
    in: path
    required: true
    type: integer
    format: int32

definitions:
  GyroInfo:
    required:
      - SampleRates
      - Ranges
    properties:
      SampleRates:
        description: Available sample rates for gyroscope measurement.
        type: array
        items:
          type: integer
          format: uint16
          x-unit: Hz
      Ranges:
        description: |
          Available ranges for angular range measurement rate. For example range
          value 500 means the range is -500...+500 dps.
        type: array
        items:
          type: integer
          format: uint16

  GyroConfig:
    required:
      - DPSRange
    properties:
      DPSRange:
        description: |
          Degree per second range. For example if set 500 the range is
          -500...+500 dps.
        type: integer
        format: uint16

  GyroData:
    required:
      - Timestamp
      - ArrayGyro
    properties:
      Timestamp:
        description: Local timestamp of first measurement.
        type: integer
        format: uint32
        x-unit: millisecond
      ArrayGyro:
        description: Measured angular velocity values (3D) in array.
        type: array
        items:
          $ref: 'http://localhost:9000/builtinTypes.yaml#/definitions/FloatVector3D'
