swagger: '2.0'

info:
  version: "0.0.1"
  title: Angular Velocity API
  description: |
    API for accessing device's angular velocity

paths:
  /Device/Measurement/AngularVelocity:
    x-executionContext: meas
    get:
      description: |
        Read the current angular velocity value.
      responses:
        200:
          description: Angular velocity vector
          schema:
            $ref: '#/definitions/AngularVelocityValue'
        204:
          description: Source is unavailable
      security:
        - suuntoAccessCode:
          - public

  /Device/Measurement/AngularVelocity/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to periodic angular velocity values.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Next value
          schema:
            $ref: '#/definitions/AngularVelocityValue'
    delete:
      description: |
        Unsubscribe periodic angular velocity subscription.
      responses:
        200:
          description: Operation completed successfully

  /Device/Measurement/AngularVelocity/HighSpeed:
    x-executionContext: meas
    
  /Device/Measurement/AngularVelocity/HighSpeed/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to high speed periodic angular velocity values.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: Next value(s)
          schema:
            $ref: '#/definitions/AngularVelocityValue'
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Unsubscribe periodic high speed angular velocity subscription.
      responses:
        200:
          description: Operation completed successfully
      security:
        - suuntoAccessCode:
          - public

definitions:
  AngularVelocityValue:
    required:
      - RelativeTime
    properties:
      RelativeTime:
        description: Relative time of measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Measurement:
        description: Angular velocity measurement(s)
        $ref: '#/definitions/FloatVector3DArray2'
        x-unit: rad/s

  FloatVector3DArray2:
    required:
      - data
    properties:
      data:
        type: array
        items:
          $ref: 'http://localhost:9000/builtinTypes.yaml#/definitions/FloatVector3D'
          