swagger: '2.0'

info:
  version: "0.0.1"
  title: LinearAcceleration API
  description: |
    API for the linear acceleration data.

paths:
  /Device/Measurement/LinearAcceleration:
    x-executionContext: meas
    get:
      description: |
        Get a linear acceleration value.
      responses:
        200:
          description: Linear acceleration vector
          schema:
            $ref: '#/definitions/LinearAccelerationValue'
        204:
          description: Measurement source is unavailable

  /Device/Measurement/LinearAcceleration/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to periodic linear acceleration values.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/LinearAccelerationValue'
    delete:
      description: |
        Unsubscribe from periodic linear acceleration values.
      responses:
        200:
          description: Operation completed successfully

  /Device/Measurement/LinearAcceleration/HighSpeed:
    x-executionContext: meas

  /Device/Measurement/LinearAcceleration/HighSpeed/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to high speed periodic linear acceleration values.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New value(s)
          schema:
            $ref: '#/definitions/LinearAccelerationValue'
    delete:
      description: |
        Unsubscribe from periodic high speed linear acceleration values.
      responses:
        200:
          description: Operation completed successfully

definitions:
  LinearAccelerationValue:
    required:
      - RelativeTime
    properties:
      RelativeTime:
        description: Relative time of measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Measurement:
        description: Linear acceleration measurement(s)
        $ref: '#/definitions/FloatVector3DArray'
        x-unit: m/s^2

  FloatVector3DArray:
    required:
      - data
    properties:
      data:
        type: array
        items:
          $ref: 'http://localhost:9000/builtinTypes.yaml#/definitions/FloatVector3D'
