swagger: '2.0'

info:
  version: 0.0.1
  title: Settings (Movesense-API)
  description: |
    This file defines the settings API for a Movesense device.

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

paths:
  /System/Settings/UartOn:
    get:
      description: |
        Gets the UART state
      responses:
        200:
          description: State updated succesfully.
      security:
        - suuntoAccessCode:
          - public
    put:
      description: |
        Sets the UART state after reset
      parameters:
      - name: State
        in: query
        required: true
        type: boolean
      responses:
        200:
          description: State updated succesfully.
      security:
        - suuntoAccessCode:
          - public

  /System/Settings/PowerOffAfterReset:
    put:
      description: |
        Orders the device to issue PowerOff after the next reset/boot-up.
        This setting automatically set to FALSE after the next reset/boot-up.
      parameters:
        - name: State
          in: query
          required: true
          type: boolean
      responses:
        200:
          description: State updated succesfully.
      security:
        - suuntoAccessCode:
          - public
    get:
      responses:
        200:
          description: State returned succesfully.
      security:
        - suuntoAccessCode:
          - public
