swagger: '2.0'

info:
  version: "0.0.1"
  title: Temperature API
  description: |
    API for measuring device's temperature.

    paths:
  /Device/Measurement/Temperature:
    x-executionContext: meas
    get:
      description: |
        Get a temperature value.
      responses:
        200:
          description: A temperature value struct with timestamp
          schema:
            $ref: '#/definitions/TemperatureValue'
        204:
          description: Measurement source is unavailable

  /Device/Measurement/Temperature/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to periodic temperature values.
        The measurement interval can be specified as parameter. The provider
        is guaranteed to provider measurements at requested interval, but may
        also send extra notifications. If 0 or left unspecified, the client
        subscribes as listener who receives results of all measurements but does
        not trigger any measurements themself.
      parameters:
        - name: Interval
          in: body
          required: false
          description: Measurement interval in seconds
          type: integer
          format: uint8
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/TemperatureValue'
    delete:
      description: |
        Unsubscribe from periodic temperature values.
      responses:
        200:
          description: Operation completed successfully

definitions:
  TemperatureValue:
    required:
      - RelativeTime
    properties:
      RelativeTime:
        description: Relative time of measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Measurement:
        description: Temperature measurement in kelvins
        type: number
        format: float
        x-unit: kelvin
