# Copyright Suunto Oy 2015-2016
# All rights reserved.

swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Device/Battery API
  description: |
    This file defines the /Device/Battery API.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths
paths:
  /Device/Battery:
    x-executionContext: meas

  /Device/Power/BatteryLevel:
    x-executionContext: meas
    get:
      description: |
        Get estimated battery charge level.
      responses:
        200:
          description: Battery charge percent
          schema:
            type: integer
            format: uint8
            x-unit: percent
      security:
        - suuntoAccessCode:
          - public

  /Device/Power/BatteryLevel/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to battery charge level change notifications.
      responses:
        200:
          description: Operation completed successfully
          schema:
            type: integer
            format: uint8
            x-unit: percent
        x-notification:
          description: New value
          schema:
            type: integer
            format: uint8
            x-unit: percent
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Unsubscribe from battery charge level change notifications.
      responses:
        200:
          description: Operation completed successfully
      security:
        - suuntoAccessCode:
          - public

  /Device/Power/BatteryState:
    x-executionContext: meas
    get:
      description: |
        Get current battery state.
      responses:
        200:
          description: Battery state enumeration
          schema:
            $ref: '#/definitions/BatteryState'
      security:
        - suuntoAccessCode:
          - public

  /Device/Power/BatteryState/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to battery state change notifications.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/BatteryState'
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Unsubscribe from battery state change notifications.
      responses:
        200:
          description: Operation completed successfully
      security:
        - suuntoAccessCode:
          - public

  /Device/Power/ChargingState:
    x-executionContext: meas
    get:
      description: |
        Get current battery charging state.
      responses:
        200:
          description: Battery charging state enumeration
          schema:
            $ref: '#/definitions/ChargingState'
        204:
          description: Measurement source is unavailable
      security:
        - suuntoAccessCode:
          - public

  /Device/Power/ChargingState/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to battery charging state change notifications.
      responses:
        200:
          description: Operation completed successfully
          schema:
            $ref: '#/definitions/ChargingState'
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/ChargingState'
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Unsubscribe from battery charging state change notifications.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe
      security:
        - suuntoAccessCode:
          - public

  /Device/Power/BatteryVoltage:
    x-executionContext: meas
    get:
      description: |
        Get measured battery voltage level.
      responses:
        200:
          description: Battery voltage level (unfiltered)
          schema:
            type: integer
            format: uint16
            x-unit: millivolt
      security:
        - suuntoAccessCode:
          - public

# Extra definitions
definitions:
  BatteryState:
    description: |
      Battery state, for use by application.
    type: integer
    format: uint8
    enum:
      - name: 'BATTERY_STATE_NOT_KNOWN'
        description: Unknown state prior to initialization or due to comm error.
        value: 1
      - name: 'BATTERY_STATE_DEAD'
        description: If we are waiting for charger but battery is dying, this is the indication sent.
        value: 2
      - name: 'BATTERY_STATE_CRITICAL'
        description: If system is starting but below needed battery level, we are critical, same during runtime.
        value: 3
      - name: 'BATTERY_STATE_LOW'
        description: LOW means training functions are not allowed to start.
        value: 4
      - name: 'BATTERY_STATE_NORMAL'
        description: All device operations are allowed from battery level perspective.
        value: 5

  ChargingState:
    description: |
      Battery charging status.
    type: integer
    format: uint8
    enum:
      - name: 'CHARGING_STATE_NOT_CHARGING'
        description: Battery is not charging.
        value: 0
      - name: 'CHARGING_STATE_CHARGING'
        description: Battery is charging.
        value: 1