# Copyright Suunto Oy 2015-2016
# All rights reserved.

swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Device/UserInteraction/Indication API
  description: |
    This file defines the /Device/UserInteraction/Indication (sound and vibra feedback effect sequence) API.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths
paths:

  /Device/UserInteraction/Indication/Play:
    x-executionContext: meas
    put:
      description: |
        Start playing the given composition. If another composition is already playing,
        the priority determines what will happen to this request. See CompositionPriority
        documentation for how different request priorities affect what happens next.
      parameters:
        - name: PlayRequest
          in: body
          required: true
          description: |
            Play request with composition effect identifier, priority and parameter values.
          schema:
            $ref: '#/definitions/PlayRequest'
      responses:
        200:
          description: Play started right away.
        202:
          description: Play request was accepted, but because of higher/same priority effect already
            playing, put into queue to be played later.
        406:
          description: Play start error
        416:
          description: Argument or parameter out of range
        424:
          description: Play request was denied because of higher priority effect already playing.
        500:
          description: driver error
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#put
      security:
        - suuntoAccessCode:
          - public

  /Device/UserInteraction/Indication/Cancel:
    x-executionContext: meas
    put:
      description: |
        Stops playing the given composition or remove it from the play request queue.
        If composition identifier is not given stop currently playing and clear all
        pending (empty request queues).
      parameters:
        - name: CompositionId
          in: body
          required: false
          description: Composition effect identifier
          schema:
            $ref: '#/definitions/CompositionId'
      responses:
        200:
          description: Operation completed successfully
        404:
          description: Not found
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#put
      security:
        - suuntoAccessCode:
          - public

  /Device/UserInteraction/Indication/Done:
    x-executionContext: meas

  /Device/UserInteraction/Indication/Done/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe the client to receive composition play finished event notifications.
      responses:
        200:
          description: Client subscribtion completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          description: |
            Identifier of the composition effect that was finished
          schema:
            $ref: '#/definitions/CompositionId'
      security:
        - suuntoAccessCode:
          - public

    delete:
      description: |
        Unsubscribe the client from composition play finished event notifications.
      responses:
        200:
          description: Client unsubscribtion completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe
      security:
        - suuntoAccessCode:
          - public

# Extra definitions
definitions:
  CompositionId:
    type: integer
    format: uint8
    minimum: 0
    maximum: 22
    description: Composition identifiers defined in Suunto Information Model (SIM)
    enum:
      - Alarm
      - AlarmDown
      - AlarmUp
      - Button
      - Confirm
      - CountdownTimer
      - Fail
      - Finished
      - Info
      - Interval
      - OverLimits
      - Phone
      - SeriousAlarm
      - SmallTargetReached
      - StartRecording
      - StartTimer
      - StopRecording
      - StopTimer
      - Success
      - TargetLost
      - TargetReached
      - UnderLimits
      - WithinLimits

  CompositionPriority:
    type: integer
    format: uint8
    enum:
      - name: 'Low'
        value: 0
        description: |
          Low priority requests will be executed only if there are no requests served
          at a time and all queues are empty. Otherwise low priority requests discarded.
      - name: 'Medium'
        value: 1
        description: |
          Medium priority requests will be placed in own FIFO queue if another
          composition is currently playing. If the queue is full, the new request
          will be discarded. The queue length is LENGTH_OF_MEDIUM_PRIORITY_PLAY_QUEUE.
      - name: 'High'
        value: 2
        description: |
          High priority requests will stop any currently playing and start the this
          composition immediately. This will not affect the queue of lower priority
          requests which will continue after high priority request is served.

  UserInteractionConfiguration:
    description: |
      Configuration of the user interaction resources.
    type: integer
    format: uint8
    enum:
      - name: 'LENGTH_OF_MEDIUM_PRIORITY_PLAY_REQUEST_QUEUE'
        value: 4

  PlayRequest:
    required:
      - CompositionId
      - CompositionPriority
    properties:
      CompositionId:
        $ref: '#/definitions/CompositionId'
      CompositionPriority:
        $ref: '#/definitions/CompositionPriority'
      SoundEnabled:
        description: |
          Tells whether sound part of this composition effect is played (if exists), true by default.
        type: boolean
      VibraEnabled:
        description: |
          Tells whether vibra part of this composition effect is played (if exists), true by default.
        type: boolean
