# Copyright Suunto Oy 2015-2016
# All rights reserved.

swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Device/Measurement/Temperature API
  description: |
    This file defines the /Device/Measurement/Temperature API.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths
paths:
  /Device/Measurement/Temperature:
    x-executionContext: meas
    get:
      description: |
        Get a temperature value.
      responses:
        200:
          description: A temperature value struct with timestamp
          schema:
            $ref: '#/definitions/TemperatureValue'
        204:
          description: Measurement source is unavailable
      security:
        - suuntoAccessCode:
          - public

  /Device/Measurement/Temperature/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to periodic temperature values.
        See documentation on product-specific measurement periods at
        http://XXX.suunto.com/XXX. If measurement source is unavailable while
        subscribed, no-type no-value is sent (periodically). This continues until
        the source is available again.

        The measurement interval can be specified as parameter. The provider
        is guaranteed to provider measurements at requested interval, but may
        also send extra notifications. If 0 or left unspecified, the client
        subscribes as listener who receives results of all measurements but does
        not trigger any measurements themself.
      parameters:
        - name: Interval
          in: body
          required: false
          description: Measurement interval in seconds
          type: integer
          format: uint8
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/TemperatureValue'
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Unsubscribe from periodic temperature values.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe
      security:
        - suuntoAccessCode:
          - public

definitions:
  TemperatureValue:
    required:
      - RelativeTime
    properties:
      RelativeTime:
        description: Relative time of measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Measurement:
        description: Temperature measurement in kelvins
        type: number
        format: float
        x-unit: kelvin
