# Copyright Suunto Oy 2016
# All rights reserved.
#
swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: Shared types
  description: |
    This file defines shared types for all Suunto API.

    See http://developer.suunto.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
      write:user: Grants write access to user profile info.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths tag is required
paths:
  x-workaround:
    x-get
      
definitions:
  VersionInfoArray:
    required:
      - versionInfo
    properties:
      versionInfo:
        type: array
        items:
          $ref: '#/definitions/VersionInfo'

  VersionInfo:
    required:
      - name
      - version
    properties:
      name:
        type: string
      version:
        type: string
       
  HeartRateQuality:
    type: integer
    format: uint8
    enum:
      - name: 'OK'
        description: Heartrate data is good
        value: 0
      - name: 'NotReliable'
        description: Heartrate data may contain errors. The sensor may be in non-optimal position and needs adjustment. 
        value: 1

  UpgradeStatus:
    required:
      - state
      - progress
    properties:
      state:
        $ref: '#/definitions/UpgradeState'
      progress:
        description: Relative progress of upgrade procedure.
        type: integer
        format: uint8
        minimum: 0
        maximum: 100
        x-unit: percent

  UpgradeState:
    description: State of upgrade procedure.
    type: integer
    format: uint8
    enum:
      - name: 'STARTED'
        description: The procedure has been started.
        value: 0
      - name: 'ONGOING'
        description: The procedure is still ongoing.
        value: 1
      - name: 'DONE'
        description: The procedure has finished successfully.
        value: 2
      - name: 'FAILURE'
        description: The procedure has terminated unsuccessfully.
        value: 3
