swagger: '2.0'

info:
  version: "0.0.1"
  title: MagneticField API
  description: |
    API for device's magnetic field measurement.
paths:
  /Device/Measurement/MagneticField:
    x-executionContext: meas
    get:
      description: |
        Get a magnetic field value.
      responses:
        200:
          description: Magnetic field vector with magnitude in microteslas
          schema:
            $ref: '#/definitions/MagneticFieldValue'
        204:
          description: Measurement source is unavailable

  /Device/Measurement/MagneticField/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to periodic magnetic field vector.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/MagneticFieldValue'
    delete:
      description: |
        Unsubscribe from periodic magnetic field values.
      responses:
        200:
          description: Operation completed successfully

definitions:
  MagneticFieldValue:
    required:
      - RelativeTime
    properties:
      RelativeTime:
        description: Relative time of measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Measurement:
        description: Magnetic field measurement in microteslas
        $ref: 'http://localhost:9000/builtinTypes.yaml#/definitions/FloatVector3D'
        x-unit: microtesla
