# Copyright Suunto Oy 2015-2016
# All rights reserved.

swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Info API
  description: |
    This file defines the /Info API.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths
paths:
  /Info:
    x-executionContext: meas
    get:
      description: |
        Query for Device Information.
      responses:
        200:
          description: Device Information structure
          schema:
            $ref: '#/definitions/DeviceInfo'
      security:
        - suuntoAccessCode:
          - public

  /Info/Version:
    x-executionContext: meas

  /Info/Version/Sw:
    x-executionContext: meas
    get:
      description: |
        Query for Device Software Version Information.
      responses:
        200:
          description: Three digit version number for the SW platform.
          schema:
            type: string
          example: "1.0.0"
      security:
        - suuntoAccessCode:
          - public

  /Info/Version/Hw:
    x-executionContext: meas
    get:
      description: |
        Query for Device Hardware Version Information.
      responses:
        200:
          description: Identifier for the HW configuration. Everytime there are changes in componets/PCB, this ID is updated.
            In Suunto case, the format is varying number of <letter, number> pairs.
          schema:
            type: string
          example: "1740G1"
      security:
        - suuntoAccessCode:
          - public

  /Info/Version/Touch:
    x-executionContext: meas
    get:
      description: |
        Query for Device Touch Controller Firmware Version Information.
      responses:
        200:
          description: Three digit version number for the Touch Controller Firmware Version
          schema:
            type: string
          example: "2.0.27"
        423:
          description: Another running request prevents getting version information
      security:
        - suuntoAccessCode:
          - public

  /Info/Version/Ble:
    x-executionContext: application
    get:
      description: |
        Query for Device BLE Controller Firmware Version Information.
      responses:
        200:
          description: Three digit version number for the BLE Controller Firmware Version
          schema:
            type: string
          example: "2.3.13"
      security:
        - suuntoAccessCode:
          - public

  /Info/Version/Gps:
    x-executionContext: meas
    get:
      description: |
        Query for Device GPS Controller Firmware Version Information.
      responses:
        200:
          description: Version identifier for the GPS controller.
          schema:
            type: string
          example: "5.7.9-P1_5.7.9"
      security:
        - suuntoAccessCode:
          - public

  /Info/Version/Ohr:
    x-executionContext: meas
    get:
      description: |
        Query for device optical heartrate sensor firmware version information. 
      responses:
        200:
          description: Version identifier for the OHR module.
          schema:
            type: string
          example: "5196"
        400:
          description: Bad request, operation failed. Returned also if optical HR sensor does not exist.
      security:
        - suuntoAccessCode:
          - public

# Extra definitions
definitions:

  DeviceInfo:
    required:
      - manufacturerName
      - productName
      - variant
      - hwCompatibilityId
      - serial
      - pcbaSerial
      - sw
      - hw
    properties:
      manufacturerName:
        description: Unique manufacturer name (this is not the original manufacturer name).
        type: string
        example: "Suunto"
      productName:
        description: Official product name visible to the consumers. This name is allocated by Suunto.
        type: string
        example: "Spartan Ultra"
      variant:
        description: Internal variant name. This name is allocated by Suunto.
        type: string
        example: "Amsterdam"
      hwCompatibilityId:
        description: Identifier defining which SW firmware can be installed on the device.
          This ID together with the variant name is used to check/fetch the latest FW.
          Different PCBAs which can run the same Firmware version have the same HwCompatibilityId.
        type: string
        example: "A"
      serial:
        description: Globally unique device serial number (12 digit)
        type: string
        example: "155110123456"
      pcbaSerial:
        description: Globally unique PCBA assemply identifier (this can be OEM specific) 
        type: string
        example: Suunto PCBA serial format = 01234112345678901234567894444N2YYWW
      sw:
        description: Three digit version number for the SW platform.
        type: string
        example: "1.0.0"
      hw:
        description: Identifier for the HW configuration. Everytime there are changes in componets/PCB, this ID is updated.
          In Suunto case, the format is varying number of <letter, number> pairs.
        type: string
        example: "1740G1"
      additionalVersionInfo:
        description: Array of structs containing pairs of version type identifier and version.
        $ref: 'http://localhost:9000/suunto_shared.yaml#/definitions/VersionInfoArray'
      addressInfo:
        description: Array of structs containing pairs of address type identifier and address.
        $ref: 'http://localhost:9000/suunto_shared.yaml#/definitions/AddressInfoArray'