# Copyright Suunto Oy 2015-2016
# All rights reserved.

swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Device/Measurement/MagneticField API
  description: |
    This file defines /Device/Measurement/MagneticField API.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths
paths:
  /Device/Measurement/MagneticField:
    x-executionContext: meas
    get:
      description: |
        Get a magnetic field value.
      responses:
        200:
          description: Magnetic field vector with magnitude in microteslas
          schema:
            $ref: '#/definitions/MagneticFieldValue'
        204:
          description: Measurement source is unavailable
      security:
        - suuntoAccessCode:
          - public

  /Device/Measurement/MagneticField/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribe to periodic magnetic field vector.
        See documentation on product-specific measurement periods at
        http://XXX.suunto.com/XXX. If measurement source is unavailable, the
        Measurement member will be empty.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/MagneticFieldValue'
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Unsubscribe from periodic magnetic field values.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe
      security:
        - suuntoAccessCode:
          - public

definitions:
  MagneticFieldValue:
    required:
      - RelativeTime
    properties:
      RelativeTime:
        description: Relative time of measurement
        type: integer
        format: uint32
        x-unit: millisecond
      Measurement:
        description: Magnetic field measurement in microteslas
        $ref: 'http://localhost:9000/builtinTypes.yaml#/definitions/FloatVector3D'
        x-unit: microtesla
