# Copyright Suunto Oy 2017
# All rights reserved.

swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Simulator API
  description: |
    This file defines the /Simulator API.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths
paths:
  /Simulator/TickMultiplier:
    x-executionContext: application
    get:
      description: Get current tick multiplier, range 1-100
      responses:
        200:
          description: Operation completed successfully
        400:
          description: Bad request
      security:
        - suuntoAccessCode:
          - public
    put:
      description: Set currently used tick multiplier, range 1-100 (For testing purposes)
      parameters:
        -
          name: value
          in: body
          description: Tick multiplier
          required: true
          schema:
            $ref: '#/definitions/TickMultiplierLimits'
      responses:
        200:
          description: Operation completed successfully
        400:
          description: Bad request
        406:
          description: Not acceptable
      security:
        - suuntoAccessCode:
          - public

definitions:
  TickMultiplierLimits:
    type: integer
    format: uint8
    enum:
      - name: MINIMUM
        value: 1
      - name: MAXIMUM
        value: 100
