swagger: '2.0'

info:
  version: "0.0.1"
  title: Device time API
  description: |
    API for reading device time.

paths:
  /Dev/Time:
    x-executionContext: meas
    get:
      description: |
        Gets current time in number of seconds since epoch 1.1.1970 (UTC).
      responses:
        200:
          description: Operation completed successfully
          schema:
            type: integer
            format: int64
    put:
      description: |
        Sets current time in number of seconds since epoch 1.1.1970 (UTC).
      parameters:
        - name: value
          in: query
          description: New time value.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribtion to the device time. 
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: |
            New time.
          schema:
            type: integer
            format: int64
    delete:
      description: |
        Unsubscribes the earlier subscription.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/DualTime:
    x-executionContext: meas
    get:
      description: |
        Gets current dual time in number of seconds since epoch 1.1.1970 (UTC), adjusted by user setting.
      responses:
        200:
          description: Operation completed successfully.
          schema:
            type: integer
            format: int64

  /Dev/Time/DualTime/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribtion to the device's dual time.
      responses:
        200:
          description: Operation completed successfully.  Returns also the current dual time.
          schema:
            type: integer
            format: int64
        x-notification:
          description: |
            New dual time.
          schema:
            type: integer
            format: int64
    delete:
      description: |
        Unsubscribes the earlier subscription.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/LocalTime:
    x-executionContext: meas
    get:
      description: |
        Gets device's local time in number of seconds since epoch 1.1.1970 (UTC) based on timezone.
      responses:
        200:
          description: Operation completed successfully
          schema:
            type: integer
            format: int64

  /Dev/Time/LocalTime/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribtion to device's local time.
      responses:
        200:
          description: Operation completed successfully. Returns also the current local time.
          schema:
            type: integer
            format: int64
        x-notification:
          description: |
            New local time.
          schema:
            type: integer
            format: int64
    delete:
      description: |
        Unsubscribes the earlier subscription.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/Min:
    x-executionContext: meas
    get:
      description: |
        Gets current time in number of seconds since epoch 1.1.1970 (UTC). Update interval is 1 min.
      responses:
        200:
          description: Operation completed successfully
          schema:
            type: integer
            format: int64

  /Dev/Time/Min/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribes to time with interval is 1 min.
      responses:
        200:
          description: Operation completed successfully. Returns time.
          schema:
            type: integer
            format: int64
        x-notification:
          description: |
            New minute time.
          schema:
            type: integer
            format: int64
    delete:
      description: |
        Unsubscribes the earlier subscription.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/DualTime/Min:
    x-executionContext: meas
    get:
      description: |
        Gets current dual time in number of seconds since epoch 1.1.1970 (UTC), adjusted by user setting. Update interval is 1 min.
      responses:
        200:
          description: Operation completed successfully
          schema:
            type: integer
            format: int64

  /Dev/Time/DualTime/Min/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribes the client to receive time change event notifications. Update interval is 1 min.
      responses:
        200:
          description: Operation completed successfully. Returns dual time.
          schema:
            type: integer
            format: int64
        x-notification:
          description: |
            New dual time minute time.
          schema:
            type: integer
            format: int64
    delete:
      description: |
        Unsubscribes the earlier subscription.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/LocalTime/Min:
    x-executionContext: meas
    get:
      description: |
        Gets current local time in number of seconds since epoch 1.1.1970 (UTC) based on timezone. Update interval is 1 min.
      responses:
        200:
          description: Operation completed successfully
          schema:
            type: integer
            format: int64

  /Dev/Time/LocalTime/Min/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribes the client to receive local time change event notifications. Update interval is 1 min.
      responses:
        200:
          description: Operation completed successfully. Returns local time.
          schema:
            type: integer
            format: int64
        x-notification:
          description: |
            New local minute time.
          schema:
            type: integer
            format: int64
    delete:
      description: |
        Unsubscribes the earlier subscription.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/DateChange:
    x-executionContext: meas

  /Dev/Time/DateChange/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscription to data change event caused by user.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: |
            New date time.
          schema:
            type: integer
            format: uint32
    delete:
      description: |
        Unsubscribes the earlier subscription.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/Midnight:
    x-executionContext: meas

  /Dev/Time/Midnight/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribed client to receive notification when the date is changed at midnight
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: |
            Date has changed at midnight indication.
          schema:
            type: boolean
    delete:
      description: |
        Unsubscribes the client from the midnight notifications.
      responses:
        200:
          description: Operation completed successfully

  /Dev/Time/Hour:
    x-executionContext: meas

  /Dev/Time/Hour/Subscription:
    x-executionContext: meas
    post:
      description: |
        Subscribed client to receive notification every hour in local timezone
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: |
            Hour has changed indication.
          schema:
            type: boolean
    delete:
      description: |
        Unsubscribes the client from hourly event notifications.
      responses:
        200:
          description: Operation completed successfully
