/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_suunto_komposti_NGBLEWrapper */

#ifndef _Included_com_suunto_komposti_NGBLEWrapper
#define _Included_com_suunto_komposti_NGBLEWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    wbSendCompleted
 * Signature: (Ljava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_wbSendCompleted
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    wbDataReceived
 * Signature: (Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_wbDataReceived
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    wbConnectCompleted
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_wbConnectCompleted
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    wbDisconnectCompleted
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_wbDisconnectCompleted
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    wbBypassConnect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_wbBypassConnect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    wbBypassDisconnect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_wbBypassDisonnect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    wbSetDelegate
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_wbSetDelegate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_suunto_komposti_NGBLEWrapper
 * Method:    setDebugLevelImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_suunto_komposti_NGBLEWrapper_setDebugLevelImpl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_suunto_komposti_NGBLEWrapper_DebugLevel */

#ifndef _Included_com_suunto_komposti_NGBLEWrapper_DebugLevel
#define _Included_com_suunto_komposti_NGBLEWrapper_DebugLevel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
