swagger: '2.0'

info:
  version: NA
  title: Linear acceleration - Movesense-API
  description: |
    This file defines interface for the linear acceleration API.
  x-api-type: public
  x-api-required: true

paths:

  /Meas/Acc/Info:
    get:
      description: |
        Get supported sample rates and ranges.
      responses:
        200:
          description: Returns accelerometer information.
          schema:
            $ref: '#/definitions/AccInfo'

  /Meas/Acc/Config:
    get:
      description: |
        Get current linear acceleration measurement configuration.
      responses:
        200:
          description: Returns accelerometer configurations.
          schema:
            $ref: '#/definitions/AccConfig'
    put:
      description: |
        Set linear acceleration measurement configuration.
      parameters:
        - name: config
          in: body
          description: New configurations for the accelerometer.
          required: true
          schema:
            $ref: '#/definitions/AccConfig'
      responses:
        200:
          description: Operation completed successfully
        503:
          description: |
            Not allowed to change configuration at the moment. E.g. when
            active subcriptions exist.

  /Meas/Acc/{SampleRate}:
    parameters:
       - $ref: '#/parameters/SampleRate'

  /Meas/Acc/{SampleRate}/Subscription:
    parameters:
       - $ref: '#/parameters/SampleRate'
    post:
      description: |
        Subscribe to periodic linear acceleration measurements.
      responses:
        200:
          description: Operation completed successfully
        501:
          description: Non-supported sample rate
        x-notification:
          description: New measurements
          schema:
            $ref: '#/definitions/AccData'
    delete:
      description: |
        Unsubscribe from periodic linear acceleration values.
      responses:
        200:
          description: Operation completed successfully

parameters:
  SampleRate:
    name: SampleRate
    in: path
    required: true
    type: integer
    format: int32

definitions:
  AccInfo:
    required:
      - SampleRates
      - Ranges
    properties:
      SampleRates:
        description: Available sample rates for acceleration measurement.
        type: array
        items:
          type: integer
          format: uint16
          x-unit: Hz
      Ranges:
        description: |
          Available ranges for acceleration measurement. For example range
          value 2 means the range is -2...+2 G.
        type: array
        items:
          type: integer
          format: uint8

  AccConfig:
    required:
      - GRange
    properties:
      GRange:
        description: |
          Acceleration range. For example if set 2 the range is -2...+2 G.
        type: integer
        format: uint8

  AccData:
    required:
      - Timestamp
      - ArrayAcc
    properties:
      Timestamp:
        description: Local timestamp of first measurement.
        type: integer
        format: uint32
        x-unit: millisecond
      ArrayAcc:
        type: array
        x-unit: m/s^2
        items:
          $ref: 'http://localhost:9000/builtinTypes.yaml#/definitions/FloatVector3D'
