swagger: '2.0'

info:
  version: NA
  title: Pressure - Movesense-API
  description: |
    This file defines interface for pressure API.
  x-api-type: public
  x-api-required: false

# Paths tag is required
paths:
  x-workaround:
    x-get

definitions:

  PressInfo:
    properties:
      Min:
        description: Minimum measurement value.
        type: number
        format: float
      Max:
        description: Maximum measurement value.
        type: number
        format: float
      Accuracy:
        description: |
          Accuracy of the measurement (with currently selected range).
        type: number
        format: float

  PressData:
    required:
      - Timestamp
      - ArrayPress
    properties:
      Timestamp:
        description: Local timestamp of first measured data.
        type: integer
        format: uint32
        x-unit: millisecond
      ArrayPress:
        type: array
        x-unit: millibar
        items:
          type: number
          format: float
