swagger: '2.0'

info:
  version: NA
  title: Gear - Movesense-API
  description: |
    API to get the globally unique Movesense ID associated with the Movesense 
    compatible physical gear
  x-api-type: public
  x-api-required: true

paths:
  /Misc/Gear/Id:
    get:
      description: |
        Get the ID associated to the physical gear (Movesense smart connector) 
        which the Movesense device is connected to.
      responses:
        200:
          description: Globally unique Movesense gear ID
          schema:
            $ref: '#/definitions/GearId'
        404:
          description: Not found.

  /Misc/Gear/Id/Subscription:
    post:
      description: |
        Subscription to Gear ID. Notification triggered when Movesense device is 
        connected to or disconnected from an extenal gear with unique ID. On 
        disconnection GearID returned is 0.
      responses:
        201:
          description: Subscription created successfully
        501:
          description: Subscription creation failed
        x-notification:
          description:
          schema:
            $ref: '#/definitions/GearId'
    delete:
      description: |
        Unsubscribe to Gear ID
      responses:
        200:
          description: Operation completed successfully

definitions:
  GearId:
    description: ID associated to the physical gear. When no external gear is connected to the Movesense device, the GearId is 0.
    type: integer
    format: uint64
