swagger: '2.0'

info:
  version: NA
  title: System debug - Movesense-API
  description: |
    This file defines the debugging and diagnostics API.
  x-api-state: experimental
  x-api-type: public
  x-api-required: false

paths:
  /System/Debug/Config:
    get:
      description: |
        Get current messages configuration.
      responses:
        200:
          description: Returns message configurations.
          schema:
            $ref: '#/definitions/DebugMessageConfig'
    put:
      description: |
        Set message configuration.
      parameters:
        - name: config
          in: body
          description: New configurations for the debug messages.
          required: true
          schema:
            $ref: '#/definitions/DebugMessageConfig'
      responses:
        200:
          description: Operation completed successfully

  /System/Debug/{Level}/Subscription:
    parameters:
        - name: Level
          in: path
          description: Debug level
          required: true
          schema:
            $ref: '#/definitions/DebugLevel'
    post:
      description: |
        Subscribe device's debug output stream.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: |
            Notification of new debug stream data.
          schema:
            $ref: '#/definitions/DebugMessage'
    delete:
      description: |
        Unsubscribe from device's debug output stream.
      responses:
        200:
          description: Operation completed successfully

  /System/Debug/Log:
    get:
      description: |
        Get debug messages from a non-volatile storage.
      parameters:
        - name: params
          in: body
          description: Range of messages to be selected.
          required: true
          schema:
            $ref: '#/definitions/DebugLogQuery'
      responses:
        200:
          description: Operation completed successfully
          schema:
            $ref: '#/definitions/DebugLogResult'
        204:
          description: No messages found in a given range.

  /System/Debug/Log/Config:
    get:
      description: |
        Get current log configuration.
      responses:
        200:
          description: Returns log configurations.
          schema:
            $ref: '#/definitions/DebugLogConfig'
    put:
      description: |
        Set log configuration.
      parameters:
        - name: config
          in: body
          description: New configurations for the debug logging.
          required: true
          schema:
            $ref: '#/definitions/DebugLogConfig'
      responses:
        200:
          description: Operation completed successfully


definitions:
  DebugMessageConfig:
    properties:
      SystemMessages:
        description: |
          Show system messages.
        type: boolean
        default: false
      UserMessages:
        description: |
          Show user messages.
        type: boolean
        default: false

  DebugLevel:
    type: integer
    format: int32
    enum:
      - name: 'Fatal'
        value: 0
      - name: 'Error'
        value: 1
      - name: 'Warning'
        value: 2
      - name: 'Info'
        value: 3
      - name: 'Verbose'
        value: 4

  DebugMessage:
    required:
      - Timestamp
      - Level
      - Tag
      - Message
    properties:
      Timestamp:
        description: Local timestamp in seconds since epoch 1.1.1970 (UTC).
        type: integer
        format: uint32
        x-unit: millisecond
      Level:
        $ref: '#/definitions/DebugLevel'
      Tag:
        description: Tag of the message.
        type: string
      Message:
        description: Debug message.
        type: string

  DebugLogQuery:
    required:
      - Timestamp
      - Count
    properties:
      Timestamp:
        description: Timestamp defining the range of debug messages (messages with older timestamps are selected).
        type: integer
        format: uint32
        x-unit: millisecond
      Count:
        description: Number of messages to be selected.
        type: integer
        format: uint16

  DebugLogConfig:
    required:
      - MinimalLevel
    properties:
      MinimalLevel:
        description: |
          Minimal level of debug messages to be saved in log.
        $ref: '#/definitions/DebugLevel'

  DebugLogResult:
    required:
      - Messages
    properties:
      Messages:
        description: List of debug messages.
        type: array
        items:
          $ref: '#/definitions/DebugMessage'
