# This file defines Suunto Whiteboard API for Connection Reliability test app
swagger: '2.0'

# Document metadata
info:
  version: "0.0.0"
  title: Movesense Connection Reliability test app API
  description: |
    This file defines API for Connection Reliability test app service

    See http://movesense.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Paths
paths:
  /Test/ConnectionReliability/IncrementSmallPkg/Subscription:
    post:
      description: |
        Subscribe to incrementing counter. 
        See documentation on product-specific measurement periods at
        http://XXX.suunto.com/XXX. If measurement source is unavailable, the
        Measurement member will be empty. If present, Measurement member
        contains single measurement result.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          schema:
              description: counter
              type: integer
              format: uint32
    delete:
      description: |
        Unsubscribe from counter
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe

  /Test/ConnectionReliability/IncrementLargePkg/Subscription:
    post:
      description: |
        Subscribe to incrementing counter with large result (64 bytes).
        See documentation on product-specific measurement periods at
        http://XXX.suunto.com/XXX. If measurement source is unavailable, the
        Measurement member will be empty. If present, Measurement member
        contains single measurement result.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          schema:
            $ref: '#/definitions/LargePkg'
    delete:
      description: |
        Unsubscribe from counter.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe


definitions:
  LargePkg:
    required:
      - counter1
      - counter2
      - counter3
      - counter4
      - counter5
      - counter6
      - counter7
      - counter8
      - counter9
      - counter10
      - counter11
      - counter12
      - counter13
      - counter14
      - counter15
      - counter16
    properties:
      counter1:
        description: counter
        type: integer
        format: uint32
      counter2:
        description: counter
        type: integer
        format: uint32
      counter3:
        description: counter
        type: integer
        format: uint32
      counter4:
        description: counter
        type: integer
        format: uint32
      counter5:
        description: counter
        type: integer
        format: uint32
      counter6:
        description: counter
        type: integer
        format: uint32
      counter7:
        description: counter
        type: integer
        format: uint32
      counter8:
        description: counter
        type: integer
        format: uint32
      counter9:
        description: counter
        type: integer
        format: uint32
      counter10:
        description: counter
        type: integer
        format: uint32
      counter11:
        description: counter
        type: integer
        format: uint32
      counter12:
        description: counter
        type: integer
        format: uint32
      counter13:
        description: counter
        type: integer
        format: uint32
      counter14:
        description: counter
        type: integer
        format: uint32
      counter15:
        description: counter
        type: integer
        format: uint32
      counter16:
        description: counter
        type: integer
        format: uint32
