# Copyright Suunto Oy 2016
# All rights reserved.
#
swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Whiteboard API
  description: |
    This file defines Suunto Whiteboard Core Services API.

    See http://developer.suunto.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com
  
# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token
    
# Paths
paths:
  /Whiteboard/Status/Flags:
    get:
      description: |
        Query Whiteboard internal status.
      responses:
        200:
          description: Operation completed successfully.
          schema:
            type: integer
            format: uint32
      security:
        - suuntoAccessCode:
          - public
