# Copyright Suunto Oy 2016
# All rights reserved.
#
swagger: '2.0'

# Document metadata
info:
  version: "0.9.0"
  title: /Whiteboard/Metrics API
  description: |
    This file defines Suunto Whiteboard Metrics Services API.

    See http://developer.suunto.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com
  
# Security definitions
security:
  - suuntoAccessCode:
    - public

securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token
    
# Paths
paths:
  /Whiteboard/Metrics/Pools:
    x-executionContext: PrimaryServices
    get:
      description: |
        Returns information about Whiteboard pools and their usage.
      responses:
        200:
          description: Operation completed successfully
          schema:
            $ref: '#/definitions/PoolStatsList'
      security:
        - suuntoAccessCode:
          - public

definitions:
  PoolStats:
    required:
      - name
      - size
      - allocated
      - highWaterMark
    properties:
      name:
        description: Name of the resource pool.
        type: string
      size:
        description: Size of the resource pool in bytes.
        type: integer
        format: uint16
      allocated:
        description: Number of currently allocated items.
        type: integer
        format: uint16
      highWaterMark:
        description: Maximum number of ever allocated items.
        type: integer
        format: uint16

  PoolStatsList:
    required:
      - pools
    properties:
      pools:
        description: List of all Whiteboard resource pools.
        type: array
        items:
          $ref: '#/definitions/PoolStats'
