#pragma once
// Copyright (c) Suunto Oy 2016. All rights reserved.

#include "whiteboard/integration/port.h"
#include "whiteboard/SystemEvent.h"

namespace whiteboard
{

/** System event function */
void WbSystemEvent(WbSystemEventModule module, WbSystemEventSeverity severity, const char* format, ...);

/** Some ports do not have config */
#ifndef WB_IS_SYSEVENT_ENABLED
#define WB_IS_SYSEVENT_ENABLED(module, severity) true
#endif

#if defined(__IAR_SYSTEMS_ICC__) || defined(__GNUC__)

#define _WB_SYSEVENT_IMPL(module, severity, ...) \
      do { if (WB_IS_SYSEVENT_ENABLED(module, severity)) \
               WbSystemEvent(module, severity, __VA_ARGS__ ); } while (0)
                                           
#define WB_SYSEVENT_API_ERROR(...)    _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_ERROR, __VA_ARGS__)
#define WB_SYSEVENT_API_WARNING(...)  _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_WARNING, __VA_ARGS__)
#define WB_SYSEVENT_API_EVENT(...)    _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_EVENT, __VA_ARGS__)
#define WB_SYSEVENT_API_TRACE(...)    _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_TRACE, __VA_ARGS__)

#define WB_SYSEVENT_COMM_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_ERROR, __VA_ARGS__)
#define WB_SYSEVENT_COMM_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_WARNING, __VA_ARGS__)
#define WB_SYSEVENT_COMM_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_EVENT, __VA_ARGS__)
#define WB_SYSEVENT_COMM_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_TRACE, __VA_ARGS__)

#define WB_SYSEVENT_DEVD_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_ERROR, __VA_ARGS__)
#define WB_SYSEVENT_DEVD_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_WARNING, __VA_ARGS__)
#define WB_SYSEVENT_DEVD_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_EVENT, __VA_ARGS__)
#define WB_SYSEVENT_DEVD_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_TRACE, __VA_ARGS__)

#define WB_SYSEVENT_MAIN_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_ERROR, __VA_ARGS__)
#define WB_SYSEVENT_MAIN_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_WARNING, __VA_ARGS__)
#define WB_SYSEVENT_MAIN_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_EVENT, __VA_ARGS__)
#define WB_SYSEVENT_MAIN_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_TRACE, __VA_ARGS__)

#define WB_SYSEVENT_PORT_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_ERROR, __VA_ARGS__)
#define WB_SYSEVENT_PORT_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_WARNING, __VA_ARGS__)
#define WB_SYSEVENT_PORT_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_EVENT, __VA_ARGS__)
#define WB_SYSEVENT_PORT_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_TRACE, __VA_ARGS__)

#define WB_SYSEVENT_ELAS_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_ERROR, __VA_ARGS__)
#define WB_SYSEVENT_ELAS_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_WARNING, __VA_ARGS__)
#define WB_SYSEVENT_ELAS_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_EVENT, __VA_ARGS__)
#define WB_SYSEVENT_ELAS_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_TRACE, __VA_ARGS__)

#define WB_SYSEVENT_JAVA_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_ERROR, __VA_ARGS__)
#define WB_SYSEVENT_JAVA_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_WARNING, __VA_ARGS__)
#define WB_SYSEVENT_JAVA_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_EVENT, __VA_ARGS__)
#define WB_SYSEVENT_JAVA_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_TRACE, __VA_ARGS__)

#else

#define _WB_SYSEVENT_IMPL(module, severity, ...) \
      do { if (WB_IS_SYSEVENT_ENABLED(module, severity)) \
               WbSystemEvent(module, severity, ## __VA_ARGS__ ); } while (0)

#define WB_SYSEVENT_API_ERROR(...)    _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_ERROR, ##__VA_ARGS__)
#define WB_SYSEVENT_API_WARNING(...)  _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_WARNING, ##__VA_ARGS__)
#define WB_SYSEVENT_API_EVENT(...)    _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_EVENT, ##__VA_ARGS__)
#define WB_SYSEVENT_API_TRACE(...)    _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_API, WB_SYSEVENT_SEVERITY_TRACE, ##__VA_ARGS__)

#define WB_SYSEVENT_COMM_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_ERROR, ##__VA_ARGS__)
#define WB_SYSEVENT_COMM_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_WARNING, ##__VA_ARGS__)
#define WB_SYSEVENT_COMM_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_EVENT, ##__VA_ARGS__)
#define WB_SYSEVENT_COMM_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_COMM, WB_SYSEVENT_SEVERITY_TRACE, ##__VA_ARGS__)

#define WB_SYSEVENT_DEVD_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_ERROR, ##__VA_ARGS__)
#define WB_SYSEVENT_DEVD_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_WARNING, ##__VA_ARGS__)
#define WB_SYSEVENT_DEVD_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_EVENT, ##__VA_ARGS__)
#define WB_SYSEVENT_DEVD_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_DEVD, WB_SYSEVENT_SEVERITY_TRACE, ##__VA_ARGS__)

#define WB_SYSEVENT_MAIN_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_ERROR, ##__VA_ARGS__)
#define WB_SYSEVENT_MAIN_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_WARNING, ##__VA_ARGS__)
#define WB_SYSEVENT_MAIN_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_EVENT, ##__VA_ARGS__)
#define WB_SYSEVENT_MAIN_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_MAIN, WB_SYSEVENT_SEVERITY_TRACE, ##__VA_ARGS__)

#define WB_SYSEVENT_PORT_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_ERROR, ##__VA_ARGS__)
#define WB_SYSEVENT_PORT_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_WARNING, ##__VA_ARGS__)
#define WB_SYSEVENT_PORT_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_EVENT, ##__VA_ARGS__)
#define WB_SYSEVENT_PORT_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_PORT, WB_SYSEVENT_SEVERITY_TRACE, ##__VA_ARGS__)

#define WB_SYSEVENT_ELAS_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_ERROR, ##__VA_ARGS__)
#define WB_SYSEVENT_ELAS_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_WARNING, ##__VA_ARGS__)
#define WB_SYSEVENT_ELAS_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_EVENT, ##__VA_ARGS__)
#define WB_SYSEVENT_ELAS_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_ELAS, WB_SYSEVENT_SEVERITY_TRACE, ##__VA_ARGS__)

#define WB_SYSEVENT_JAVA_ERROR(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_ERROR, ##__VA_ARGS__)
#define WB_SYSEVENT_JAVA_WARNING(...) _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_WARNING, ##__VA_ARGS__)
#define WB_SYSEVENT_JAVA_EVENT(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_EVENT, ##__VA_ARGS__)
#define WB_SYSEVENT_JAVA_TRACE(...)   _WB_SYSEVENT_IMPL(WB_SYSEVENT_ID_JAVA, WB_SYSEVENT_SEVERITY_TRACE, ##__VA_ARGS__)

#endif

}

