
// This file contains system events only for WB. They are defined here
// so that whiteboard nea BSP finds them....

// XXXX TODO: This still needs to be implemented!!!!

#define SYSEVENT_WBAPI_ERROR
#define SYSEVENT_WBAPI_WARNING
#define SYSEVENT_WBAPI_EVENT
#define SYSEVENT_WBAPI_TRACE

#define SYSEVENT_WBCOMM_ERROR
#define SYSEVENT_WBCOMM_WARNING
#define SYSEVENT_WBCOMM_EVENT
#define SYSEVENT_WBCOMM_TRACE

#define SYSEVENT_WBDEVD_ERROR
#define SYSEVENT_WBDEVD_WARNING
#define SYSEVENT_WBDEVD_EVENT
#define SYSEVENT_WBDEVD_TRACE

#define SYSEVENT_WBMAIN_ERROR
#define SYSEVENT_WBMAIN_WARNING
#define SYSEVENT_WBMAIN_EVENT
#define SYSEVENT_WBMAIN_TRACE

#define SYSEVENT_WBPORT_ERROR
#define SYSEVENT_WBPORT_WARNING
#define SYSEVENT_WBPORT_EVENT
#define SYSEVENT_WBPORT_TRACE
