# This file defines the API namespace and related operations for Movesense accelerometer integer value sample app
swagger: '2.0'

# Document metadata
info:
  version: "0.1.0"
  title: Movesense accelerometer integer value sample app API
  description: |
    This file defines API for Movesense accelerometer integer value sample service interface.
    See http://movesense.com for more information.
  termsOfService: http://movesense.com
  contact:
    name: Suunto team
    url: http://movesense.com

paths:
  /Sample/IntAcc/{SampleRate}/Subscription:
    parameters:
      - $ref: 'http://localhost:9000/acc.yaml#/parameters/SampleRate' # reference sample rate parameter from movesense-api spec
    post:
      description: |
        Subscribe to periodic linear acceleration measurement integer values. Wraps to /Meas/Acc/{SampleRate}/Subscription.
        Use /Meas/Acc/Info and /Meas/Acc/Config operations in conjunction with this sample API if needed.
      responses:
        200:
          description: Operation completed successfully
        423:
          description: Too many simultaneous subscriptions to /Sample/IntAcc/{SampleRate}
        501:
          description: Non-supported sample rate
        x-notification:
          description: New measurements
          schema:
            $ref: '#/definitions/IntAccData'
    delete:
      description: |
        Unsubscribe from periodic linear acceleration values.
      responses:
        200:
          description: Operation completed successfully
        404:
          description: Client tried to unsubscribe a sample rate it had not subscribed.

definitions:
  Int16Vector3D:
    required:
    - x
    - y
    - z
    properties:
      x:
        type: integer
        format: int16
      y:
        type: integer
        format: int16
      z:
        type: integer
        format: int16

  IntAccData:
    required:
      - Timestamp
      - ArrayAcc
    properties:
      Timestamp:
        description: Local timestamp of first measurement.
        type: integer
        format: uint32
        x-unit: millisecond
      ArrayAcc:
        description: The G range salected via /Meas/Acc/Config is scaled between INT16_MIN and INT16_MAX (-32767 and 32767).
        type: array
        x-unit: m/s^2
        items:
          $ref: '#/definitions/Int16Vector3D'
