swagger: '2.0'

info:
  version: NA
  title: Time - Movesense-API
  description: |
    API for setting and reading device EPOCH time.
  x-api-type: public
  x-api-required: true

paths:
  /Time:
    get:
      description: |
        Gets current time in number of microseconds since epoch 1.1.1970 (UTC).
        If not explicitly set, contains time 2015-01-01 0:00 or earlier depending on the implementation.
      responses:
        200:
          description: Operation completed successfully
          schema:
            type: integer
            format: int64
    put:
      description: |
        Sets current time in number of microseconds since epoch 1.1.1970 (UTC).
      parameters:
        - name: value
          in: query
          description: New time value.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Operation completed successfully

  /Time/Subscription:
    post:
      description: |
        Subscription to the device time. Notifications are given every second.
      responses:
        200:
          description: Operation completed successfully
        x-notification:
          description: |
            Current time in microseconds since epoch 1.1.1970 (UTC).
          schema:
            type: integer
            format: int64
    delete:
      description: |
        Unsubscribes an active subscription.
      responses:
        200:
          description: Operation completed successfully

  /Time/Detailed:
    get:
      description: |
        Gets all current time related info in one go. This enables knowledge of RelativeTime 
        and UTC time at the same instance, which is needed in multisensor use cases.
      responses:
        200:
          description: Operation completed successfully
          schema:
            $ref: '#/definitions/DetailedTime'


definitions:

  DetailedTime:
    required:
      - utcTime
      - relativeTime
      - tickRate
    properties:
      utcTime:
        description: UTC time of the device, number of microseconds since epoch 1.1.1970 (UTC).
        type: integer
        format: int64
      relativeTime:
        description: Local time of the device, milliseconds since device reset.
        type: integer
        format: uint32
        x-unit: millisecond
      tickRate:
        description: Tick rate of the device clock in ticks per second (Hz). This specifies the real resolution of the device clock.
        type: integer
        format: uint32
        x-unit: hertz
      accuracy:
        description: | 
          The nominal accuracy of the device clock in parts per million (ppm). 
          The actual accuracy depends on many things (device temperature, vibration environment etc.).
        type: integer
        format: uint32
