swagger: '2.0'

info:
  version: NA
  title: Common types - Movesense-API
  description: |
    Commonly available types in addition to Whiteboard built-in types.
  x-api-type: public
  x-api-required: true

paths:
  x-workaround:
    x-get

definitions:

  VersionInfoArray:
    required:
      - versionInfo
    properties:
      versionInfo:
        type: array
        items:
          $ref: '#/definitions/VersionInfo'

  VersionInfo:
    required:
      - name
      - version
    properties:
      name:
        type: string
        minLength: 1
        maxLength: 16
      version:
        type: string
        minLength: 1
        maxLength: 16

  AddressInfo:
    required:
      - name
      - address
    properties:
      name:
        description: Address type (BLE, WIFI)
        type: string
        example: BLE
        minLength: 3
        maxLength: 16
      address:
        description: Address value
        type: string
        example: 80-1F-02-4E-F1-70
        minLength: 1
        maxLength: 16

  HRData:
    required:
      - average
      - rrData
    properties:
      average:
        description: |
            Heart rate value that is averaged and filtered and presented in bpm.
            Invalid heart rate is presented by 0.0f.
        type: number
        format: float
        x-unit: bpm
        minimum: 0.0
        maximum: 250.0
      rrData:
        description: |
            RR-interval returns all the intervals in milliseconds. By default,
            single rr-interval value is returned after each heart beat.
        type: array
        minItems: 1
        maxItems: 60
        items:
          type: integer
          format: uint16
          x-unit: ms
          minimum: 240    # equals in HR 250 bpm
          maximum: 4000   # equals in HR 15 bpm

  TimestampFromStartup:
    description: Milliseconds since the startup (e.g. like reset or so).
    type: integer
    format: uint64
    x-unit: millisecond

  MacAddress48:
    type: string
    description: IEEE 802 48-bit device MAC address
    example: 00:14:22:01:23:45
    minLength: 17
    maxLength: 17
