# This file defines Suunto Whiteboard API for Movesense Hackathon 2016 sample
#
swagger: '2.0'

# Document metadata
info:
  version: "0.0.0"
  title: Movesense Jump meter sample app API
  description: |
    This file defines API for Movesense Jump meter Sample service

    See http://movesense.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Paths
paths:
  /Sample/JumpCounter/JumpCount:
    get:
      description: |
        Get a Data value.
      responses:
        200:
          schema:
              description: Detected jump count
              type: integer
              format: uint16

        204:
          description: Measurement source is unavailable

  /Sample/JumpCounter/JumpCount/Subscription:
    post:
      description: |
        Subscribe to periodic Data values.
        See documentation on product-specific measurement periods at
        http://XXX.suunto.com/XXX. If measurement source is unavailable, the
        Measurement member will be empty. If present, Measurement member
        contains single measurement result.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          schema:
              description: Detected jump count
              type: integer
              format: uint16
    delete:
      description: |
        Unsubscribe from jump count updates
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe

  /Sample/JumpCounter/LastJumpHeight:
    get:
      description: |
        Get a Data value.
      responses:
        200:
          schema:
              description: Last jump height in meters
              type: number
              format: float
              x-unit: m
        204:
          description: Measurement source is unavailable

  /Sample/JumpCounter/LastJumpHeight/Subscription:
    post:
      description: |
        Subscribe to periodic Data values.
        See documentation on product-specific measurement periods at
        http://XXX.suunto.com/XXX. If measurement source is unavailable, the
        Measurement member will be empty. If present, Measurement member
        contains single measurement result.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          schema:
              description: Last jump height in meters
              type: number
              format: float
              x-unit: m
    delete:
      description: |
        Unsubscribe from jump height updates.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe


definitions:
  JumpInfo:
    required:
      - RelativeTime
      - Value
    properties:
      RelativeTime:
        description: Relative time of jump
        type: integer
        format: uint32
        x-unit: millisecond
      Value:
        description: Last jump height in meters
        type: number
        format: float
        x-unit: m
