#include "movesense.h"
#include "HelloWorldService.h"
#include "AccelerometerSampleService.h"

MOVESENSE_APPLICATION_STACKSIZE(1024)
 
MOVESENSE_PROVIDERS_BEGIN(2)

MOVESENSE_PROVIDER_DEF(HelloWorldService)
MOVESENSE_PROVIDER_DEF(AccelerometerSampleService)

MOVESENSE_PROVIDERS_END(2)

MOVESENSE_FEATURES_BEGIN()
    SERIAL_COMMUNICATION(true)
    BLE_COMMUNICATION(true)
MOVESENSE_FEATURES_END()
