# This file defines Suunto Whiteboard API for Movesense Hackathon 2016 sample
#
swagger: '2.0'

# Document metadata
info:
  version: "0.0.1"
  title: Movesense API 1wire thermometer example
  description: |
    This file defines the API for 1wire thermometer example app

    See http://movesense.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Paths
paths:
  /Sample/1WireTemp:
    get:
      description: |
        Get measurement from all attached 1wire thermometers
      responses:
        200:
          description: Temperature data
          schema:
            $ref: '#/definitions/ExtTempMeasurements'
        400:
          description: There is too many ongoing requests. Please wait and try again later
        503:
          description: Service unavailable

definitions:
  ExtTempMeasurements:
    required:
      - Measurements
    properties:
      Measurements:
        description: External temperature sensor measurements
        type: array
        items:
          $ref: '#/definitions/TempMeasurement'

  TempMeasurement:
    required:
      - DeviceId      
      - Temperature
    properties:
      DeviceId:
        description: Id of the 1wire thermometer
        type: integer
        format: uint64
      Temperature:
        description: Temperature result in Kelvin
        type: number
        format: float
        x-unit: kelvin
