#pragma once

/******************************************************************************

Copyright (c) Suunto Oy 2016.
All rights reserved.

******************************************************************************/

/*
 * System Event logging configuration macros.
 *
 * Note - this file is autogenerated. It needs to be re-generated when new module IDs are added.
 */

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_FAULT_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FAULT_EVENT_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FAULT_EVENT_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FAULT_EVENT_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_WBAPI
#define ENABLE_NEA_SYSTEM_EVENT_ID_WBAPI_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBAPI_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBAPI_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_WBCOMM
#define ENABLE_NEA_SYSTEM_EVENT_ID_WBCOMM_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_WBCOMM_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBCOMM_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_WBDEVD
#define ENABLE_NEA_SYSTEM_EVENT_ID_WBDEVD_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBDEVD_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBDEVD_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_WBMAIN
#define ENABLE_NEA_SYSTEM_EVENT_ID_WBMAIN_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_WBMAIN_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBMAIN_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_WBPORT
#define ENABLE_NEA_SYSTEM_EVENT_ID_WBPORT_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBPORT_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WBPORT_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_SCHEDULER
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SCHEDULER_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SCHEDULER_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SCHEDULER_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_MPU
// #define ENABLE_NEA_SYSTEM_EVENT_ID_MPU_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_MPU_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_MPU_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_WATCHDOG
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WATCHDOG_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WATCHDOG_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WATCHDOG_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_POWER_STATE
#define ENABLE_NEA_SYSTEM_EVENT_ID_POWER_STATE_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_POWER_STATE_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_POWER_STATE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_DRT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_DRT_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_DRT_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_DRT_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_BOOTLOOP
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BOOTLOOP_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_BOOTLOOP_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BOOTLOOP_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_SPI
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SPI_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SPI_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SPI_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_I2C
// #define ENABLE_NEA_SYSTEM_EVENT_ID_I2C_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_I2C_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_I2C_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_UART
// #define ENABLE_NEA_SYSTEM_EVENT_ID_UART_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_UART_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_UART_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_BLE
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BLE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BLE_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_BLE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_WIFI
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WIFI_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WIFI_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_WIFI_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_LOGGER
#define ENABLE_NEA_SYSTEM_EVENT_ID_LOGGER_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_LOGGER_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_LOGGER_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_FILESYSTEM
#define ENABLE_NEA_SYSTEM_EVENT_ID_FILESYSTEM_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FILESYSTEM_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_FILESYSTEM_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_SPEEDFUSION
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SPEEDFUSION_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_SPEEDFUSION_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SPEEDFUSION_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_SPEEDFUSION
#define ENABLE_NEA_SYSTEM_EVENT_ID_ALTIFUSION_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_ALTIFUSION_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_ALTIFUSION_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_INTERCHIP
// #define ENABLE_NEA_SYSTEM_EVENT_ID_INTERCHIP_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_INTERCHIP_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_INTERCHIP_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_SETTINGS
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SETTINGS_WARNING
//#define ENABLE_NEA_SYSTEM_EVENT_ID_SETTINGS_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_SETTINGS_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_COMPASS
// #define ENABLE_NEA_SYSTEM_EVENT_ID_COMPASS_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_COMPASS_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_COMPASS_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_PERIPHERAL_FIRMWARE
#define ENABLE_NEA_SYSTEM_EVENT_ID_PERIPHERAL_FIRMWARE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_PERIPHERAL_FIRMWARE_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_PERIPHERAL_FIRMWARE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_FWUPDATE
#define ENABLE_NEA_SYSTEM_EVENT_ID_FWUPDATE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FWUPDATE_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FWUPDATE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_ACTIVITY
// #define ENABLE_NEA_SYSTEM_EVENT_ID_ACTIVITY_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_ACTIVITY_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_ACTIVITY_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_NAVIGATION
// #define ENABLE_NEA_SYSTEM_EVENT_ID_NAVIGATION_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_NAVIGATION_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_NAVIGATION_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_LAPENGINE
#define ENABLE_NEA_SYSTEM_EVENT_ID_LAPENGINE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_LAPENGINE_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_LAPENGINE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_SYNC
#define ENABLE_NEA_SYSTEM_EVENT_ID_SYNC_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_SYNC_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_SYNC_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_TRAININGLAB
#define ENABLE_NEA_SYSTEM_EVENT_ID_TRAININGLAB_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_TRAININGLAB_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_TRAININGLAB_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_SLEEP
#define ENABLE_NEA_SYSTEM_EVENT_ID_SLEEP_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_SLEEP_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_SLEEP_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_APPLICATION
#define ENABLE_NEA_SYSTEM_EVENT_ID_APPLICATION_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_APPLICATION_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_APPLICATION_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_UI_FRAMEWORK
#define ENABLE_NEA_SYSTEM_EVENT_ID_UI_FRAMEWORK_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_UI_FRAMEWORK_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_UI_FRAMEWORK_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_DUKTAPE
#define ENABLE_NEA_SYSTEM_EVENT_ID_DUKTAPE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_DUKTAPE_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_DUKTAPE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_MAGNETOMETER
// #define ENABLE_NEA_SYSTEM_EVENT_ID_MAGNETOMETER_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_MAGNETOMETER_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_MAGNETOMETER_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_GPS
#define ENABLE_NEA_SYSTEM_EVENT_ID_GPS_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_GPS_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_GPS_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_DISPLAY
// #define ENABLE_NEA_SYSTEM_EVENT_ID_DISPLAY_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_DISPLAY_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_DISPLAY_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_TOUCH
// #define ENABLE_NEA_SYSTEM_EVENT_ID_TOUCH_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_TOUCH_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_TOUCH_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_ACCELEROMETER
#define ENABLE_NEA_SYSTEM_EVENT_ID_ACCELEROMETER_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_ACCELEROMETER_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_ACCELEROMETER_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_GYROSCOPE
// #define ENABLE_NEA_SYSTEM_EVENT_ID_GYROSCOPE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_GYROSCOPE_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_GYROSCOPE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_VIBRA
// #define ENABLE_NEA_SYSTEM_EVENT_ID_VIBRA_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_VIBRA_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_VIBRA_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_BUZZER
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BUZZER_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BUZZER_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BUZZER_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_EXT_FLASH
// #define ENABLE_NEA_SYSTEM_EVENT_ID_EXT_FLASH_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_EXT_FLASH_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_EXT_FLASH_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_INT_FLASH
// #define ENABLE_NEA_SYSTEM_EVENT_ID_INT_FLASH_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_INT_FLASH_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_INT_FLASH_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_PMIC
#define ENABLE_NEA_SYSTEM_EVENT_ID_PMIC_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_PMIC_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_PMIC_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_FUEL_GAUGE
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FUEL_GAUGE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_FUEL_GAUGE_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_FUEL_GAUGE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_BUTTON
#define ENABLE_NEA_SYSTEM_EVENT_ID_BUTTON_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BUTTON_EVENT
// #define ENABLE_NEA_SYSTEM_EVENT_ID_BUTTON_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_PRESSURE
// #define ENABLE_NEA_SYSTEM_EVENT_ID_PRESSURE_WARNING
// #define ENABLE_NEA_SYSTEM_EVENT_ID_PRESSURE_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_PRESSURE_TRACE

// Uncomment one of the below macros to enable system event logging for module SYSTEM_EVENT_ID_OHR
#define ENABLE_NEA_SYSTEM_EVENT_ID_OHR_WARNING
#define ENABLE_NEA_SYSTEM_EVENT_ID_OHR_EVENT
#define ENABLE_NEA_SYSTEM_EVENT_ID_OHR_TRACE
