# This file defines Suunto Whiteboard API for Movesense Hackathon 2016 sample
#
swagger: '2.0'

# Document metadata
info:
  version: "0.0.1"
  title: Movesense API Hello World example
  description: |
    This file defines the API for Hello World example

    See http://movesense.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com
  

# Security definitions
security:
  - suuntoAccessCode:
    - public
    
securityDefinitions:
  suuntoAccessCode:
    type: oauth2
    scopes:
      public: Grants read/write access to public resources.
    flow: accessCode
    authorizationUrl: https://suunto.com/wbapi/login/oauth/authorize
    tokenUrl: https://suunto.com/wbapi/login/oauth/access_token

# Paths
paths:
  /Example/HelloWorld:
    x-executionContext: application
    get:
      description: |
        Get a "Hello World" value
      responses:
        200:
          description: Sample service data (in practice acceleration magnitude)
          schema:
            $ref: '#/definitions/HelloWorldValue'
      security:
        - suuntoAccessCode:
          - public

  /Example/HelloWorld/Subscription:
    x-executionContext: application
    post:
      description: |
        Get a "Hello World" values.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          description: New value
          schema:
            $ref: '#/definitions/HelloWorldValue'
      security:
        - suuntoAccessCode:
          - public
    delete:
      description: |
        Unsubscribe from sample data values.
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe
      security:
        - suuntoAccessCode:
          - public


definitions:
  HelloWorldValue:
    required:
      - Greeting
    properties:
      Greeting:
        description: Hello World greeting
        type: string
