swagger: '2.0'

# Document metadata
info:
  version: "0.0.0"
  title: Movesense Test sample app API
  description: |
    This file defines API for Movesense Test Sample service

    See http://movesense.com for more information.
  termsOfService: http://suunto.com/wbapi/terms/
  contact:
    name: Suunto team
    url: http://developer.suunto.com

# Paths
paths:
  /Sample/SensorOutput/Config:
    get:
      description: |
        Get current test configuration.
      responses:
        200:
          description: Returns configurations.
          schema:
            $ref: '#/definitions/TestConfig'
    put:
      description: |
        Set configuration.
      parameters:
        - name: config
          in: body
          description: New configurations for the test.
          required: true
          schema:
            $ref: '#/definitions/TestConfig'
      responses:
        200:
          description: Operation completed successfully
        503:
          description: |
            Not allowed to change configuration at the moment. E.g. when
            active subcriptions exist.

  /Sample/SensorOutput/Subscription:
    post:
      description: |
        Subscribe
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          schema:
              $ref: '#/definitions/TestResult'
    delete:
      description: |
        Unsubscribe
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe

definitions:
  TestConfig:
    type: object
    required:
      - path
      - period
      - sampleRate
    properties:
      path:
        description: |
          path for tested data
        type: string
      period:
        description: |
          Testing time in seconds
        type: integer
        format: int32
      sampleRate:
        description: |
          Sensor sample rate
        type: integer
        format: int32

  TestResult:
    required:
      - probesGood
      - probesBad
      - gaps
    properties:
      probesGood:
        description: |
          Counted in range probes during testing period
        type: integer
        format: uint32
      probesBad:
        description: |
          Counted out of range probes during testing period
        type: integer
        format: uint32
      gaps: 
        description: |
          Counted gaps in timestamps during testing period
        type: integer
        format: uint32
